# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/30f05e80-acac-471a-9780-85495c402db2";
      fsType = "btrfs";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/30f05e80-acac-471a-9780-85495c402db2";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/30f05e80-acac-471a-9780-85495c402db2";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CD78-6CAE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/gamesDrive" = 
    { device = "/dev/disk/by-uuid/69e921e6-caf4-4419-9a4e-b6824a62f24e";
      fsType = "btrfs";
      options = [ "nofail" ];
    };

  fileSystems."/mnt/randomCrap" = 
    { device = "/dev/disk/by-uuid/76430670-b39a-4ae6-b28f-44752ffc167c";
      fsType = "btrfs";
      options = [ "nofail" ];
    };

  fileSystems."/mnt/slowSSD" = 
    { device = "/dev/disk/by-uuid/efff4361-0b5e-41be-a48f-80eded819ba0";
      fsType = "btrfs";
      options = [ "nofail" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
